version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3



  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////code/data/shortener.db
      - REDIS_HOST=redis  # Redis service name
      - REDIS_PORT=6379
      - REDIS_TTL_SECONDS=259200
      - RATE_LIMIT_PER_IP=100
      - RATE_LIMIT_WINDOW=3600
      - BASE_URL=http://localhost:8000
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - sqlite_data:/code/data
    restart: unless-stopped

volumes:
  redis_data:
  sqlite_data: